### ISSUE TITLE
bootstrap is not defined

### ISSUE THREAD

**Issue by jiraph** [ducng99/SBBCoolHelper#10]
All buttons except Set UserID are no longer working. Console says "Uncaught ReferenceError: bootstrap is not defined".

![Screenshot 2022-08-06 151914](https://user-images.githubusercontent.com/19298861/183267689-2008256c-7873-42c2-a8dd-502c2102bf1f.png)

Firefox 103.0.1    Tampermonkey v4.17.6161

**Comment by ducng99** [comment]
The script is still functional.
That error means bootstrap js is not loaded. In the console, what shows up if you type in `bootstrap`?

**Comment by jiraph** [comment]
Ah yes, I tried on chromium and it still worked - I should have mentioned that. I also tried reinstalling the script and disabling all other userscripts, but it didn't help.

Is this what you're after?
![Screenshot 2022-08-06 162037](https://user-images.githubusercontent.com/19298861/183268837-28dc3dc4-b24c-4c74-ad57-d132ce4eaf23.png)

**Comment by ducng99** [comment]
Yes, that's it.
Not sure why this is happening for you, bootstrap is used by SBB and not just this script. 
Can you confirm you have this `<script>` tag in Inspector?
![image](https://user-images.githubusercontent.com/49080794/183270664-736ab657-5b41-4567-acff-498135243b4d.png)

Also, are you able to access https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js?
Something might've blocked it from loading?

**Comment by jiraph** [comment]
Yep, 🤦‍♂️ another extension I have, LocalCDN, wasn't able to load bootstrap properly on sb.ltn.fi. Changing some options for it fixed the problem. Thanks for the help 👍

**Comment by ducng99** [comment]
No worries!
