### ISSUE TITLE
[Question] Purpose of "Set UserID"

### ISSUE THREAD

**Issue by misterpyrrhuloxia** [ducng99/SBBCoolHelper#11]
Can you please explain what the purpose is of `Set UserID`?

![image](https://github.com/ducng99/SBBCoolHelper/assets/9469151/b8893294-3334-4807-989b-ca580cf03551)

**Comment by ducng99** [comment]
Hi ya, after setting the user ID (your SponsorBlock private user ID), you'll be able to use the features of this script, specified here: https://github.com/ducng99/SBBCoolHelper#features
